### PR TITLE
Split mega-app into separate parts.

### PR DESCRIPTION
**Pull request by jezdez**
This does:

- Introduce "clusters", "jobs" and "workers" apps
- Remove "base" app
- Move templates and static files into main Python package
- Move kronos jobs into apps
- Add initial database migrations

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/7)

### CODE REVIEW

**Comment by jezdez** [comment]
@maurodoglio Sorry for the lateness of my push, this is the test-passing state of my work. It may need to be rebased on the current master though..

**Comment by jezdez** [comment]
BTW, I think it would be awesome to rename the main project from `analysis_service` to just `atmo`. The import paths look just a bit nicer then :)

**Comment by maurodoglio** [comment]
:lgtm:

---

Reviewed 124 of 124 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-analysis-service/7#-:-KOGFK3TEhPu2dTBzTC9:1417088721)*

**Comment by jezdez** [comment]
Huzzah!

**Pull request merged**
