### PR TITLE
Bug 1316001 - Add 5.2.0 to the list of EMR releases

### PR DESCRIPTION
**Pull request by marco-c**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/90)

### CODE REVIEW

**Comment by maurodoglio** [comment]
I verified that the telemetry hello world notebook runs on emr 5.2, both on a manually spawn cluster and as a job.

**Comment by jezdez** [comment]
@maurodoglio r+

**Comment by jezdez** [comment]
What about 5.2.1 btw?

**Comment by maurodoglio** [comment]
I haven't tried it yet. I'll do it in a few.

**Comment by maurodoglio** [comment]
5.2.1 works as well in my tests.

**Comment by maurodoglio** [comment]
@jezdez we still need to generate the automatic migration though

**Pull request closed without merging**
