### PR TITLE
Bug 1312983 - Make job identifier immutable

### PR DESCRIPTION
**Pull request by maurodoglio**

### CODE REVIEW

**Comment by maurodoglio** [comment]
@jezdez r?

**Comment by jezdez** [comment]
I'm not following, why do you want to remove editing job details?

**Comment by maurodoglio** [comment]
I disabled editing the job identifier in the job edit form and I removed the cluster edit view completely because the only value that was edited there was the cluster identifier. This seems to have little value for the end users and we want to use the cluster and job identifiers as part of the path to their logs.

**Comment by jezdez** [comment]
@maurodoglio Ah, right, makes sense.

**Pull request merged**
