### PR TITLE
Bug 1307528 - Backup log files to s3

### PR DESCRIPTION
**Pull request by maurodoglio**
I updated @fbertsch code and rebased it on top of latest master.

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by jezdez** [comment]
LGTM r+

**Comment by jezdez** [comment]
Oh one thing, we may want to delete the logs of terminated clusters and deleted jobs to prevent overwrites with new clusters/jobs with he same identifier.

**Comment by fbertsch** [comment]
@jezdez We don't want to overwrite since we'll need to use these logs to debug problems in the cluster, especially after shutdown. I don't think there will be overwrite since the folder includes the timestamp, do you agree? E.g. later created clusters with the same identifier will have a different log directory.

**Comment by jezdez** [comment]
@fbertsch Yeah, timestamp is good, but keeping every log ever is not going to help finding the logs we need. @maurodoglio said there is a way to set a bucket level expiration policy

**Comment by maurodoglio** [comment]
I set the bucket expiration policy to 61 days.

**Comment by maurodoglio** [comment]
Thanks for the patch @fbertsch 😸

**Comment by fbertsch** [comment]
Thanks for fixing it up guys 🎉

**Pull request merged**
